const express = require('express');
const app = express();
const db = require('./db');
const bodyParser = require('body-parser');
const personRoutes = require('./routes/user');
const menuRoutes = require('./routes/menu.route');
app.use(bodyParser.json());
app.use('/person',personRoutes);
app.use('/menu', menuRoutes);
app.listen(3000, () => { console.log("Listening on port 3000") });